### ISSUE TITLE
The script to download images is not available

### ISSUE THREAD

**Issue by gururaj-bhat** [dnuffer/open_images_downloader#1]
In README it is mentioned : 
Open Images Downloader is distributed with a shell script and batch file generated by sbt-native-packager (http://www.scala-sbt.org/sbt-native-packager/index.html), so all you need to run it is to download and extract the distribution and then execute open_images_downloader (or the .bat on windows)  

But the script open_images_downloader (or .bat file for windows for that matter) is not available by default in the repo.  
Do we need to build the scala project by ourselves to generate those scripts?

**Comment by dnuffer** [comment]
The scripts are generated by the build process and are contained in the release archives. You can download the appropriate archive from https://github.com/dnuffer/open_images_downloader/releases. Or if you just checkout the repo you can generate them by running `sbt universal:packageZipTarball`
